# Generated by Django 5.1.1 on 2025-10-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
