# Generated by Django 5.1.1 on 2025-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_ingredients"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="tags.tag"
            ),
        ),
    ]
